import type { IncidentSeverity, IncidentType } from '../types/incident.types'

export interface TriageInput { type: IncidentType; description: string; peopleAffected: number }
export interface TriageResult { severity: IncidentSeverity; score: number; confidence: number; reasons: string[] }
const baseScores: Record<IncidentType, number> = { structural_collapse: 48, fire: 45, flood: 35, medical: 35, accident: 28, earthquake: 52, hazmat: 52, other: 15 }
const typeReasons: Record<IncidentType, string> = { structural_collapse: 'Structural collapse reported', fire: 'Fire emergency reported', flood: 'Flood emergency reported', medical: 'Medical emergency reported', accident: 'Road accident reported', earthquake: 'Earthquake incident reported', hazmat: 'Hazardous materials risk reported', other: 'Citizen emergency report received' }
const dangerSignals: Array<[string, number, string]> = [['people inside', 11, 'People may be inside the danger area'], ['unconscious', 15, 'Unconscious person reported'], ['trapped', 12, 'People may be trapped'], ['multiple', 8, 'Multiple casualties or people involved'], ['injured', 7, 'Injuries reported'], ['bleeding', 11, 'Bleeding reported'], ['collapsed', 10, 'Collapse risk reported'], ['smoke', 6, 'Smoke reported'], ['spreading', 9, 'Hazard is spreading'], ['evacuate', 8, 'Evacuation may be required'], ['children', 8, 'Children may be affected'], ['dead', 14, 'Possible fatalities reported'], ['critical', 8, 'Critical conditions reported'], ['stranded', 12, 'People are stranded'], ['major accident', 8, 'Major accident indicated']]
const catastrophicSignals: Array<[string, number, string]> = [['plane crash', 30, 'Aircraft/plane crash detected'], ['aircraft crash', 30, 'Aircraft/plane crash detected'], ['explosion', 28, 'Explosion risk reported'], ['building collapse', 28, 'Building collapse detected'], ['structural collapse', 28, 'Structural collapse detected'], ['mass casualty', 28, 'Mass-casualty event indicated'], ['multiple casualties', 25, 'Multiple casualties reported'], ['widespread fire', 28, 'Widespread fire reported'], ['major hazardous-material release', 28, 'Major hazardous-material release reported'], ['major hazmat release', 28, 'Major hazardous-material release reported']]
const mitigatingSignals: Array<[string, number, string]> = [['no injuries', -15, 'No injuries reported'], ['empty building', -10, 'Building reported empty'], ['contained', -13, 'Hazard reported contained'], ['minor', -9, 'Incident described as minor'], ['small', -10, 'Incident described as small']]
const peopleScore = (people: number) => people === 0 ? 0 : people === 1 ? 5 : people <= 5 ? 12 : people <= 20 ? 22 : 30
const peopleReason = (people: number) => people === 0 ? 'No people reported affected' : `${people} ${people === 1 ? 'person' : 'people'} reported affected`
const severityFor = (score: number): IncidentSeverity => score >= 75 ? 'critical' : score >= 50 ? 'high' : score >= 25 ? 'medium' : 'low'

export function triageIncident({ type, description, peopleAffected }: TriageInput): TriageResult { const normalDescription = description.toLowerCase(); const reasons = [typeReasons[type], peopleReason(peopleAffected)]; let score = baseScores[type] + peopleScore(peopleAffected); let signals = 0; let catastrophicCount = 0; for (const [keyword, adjustment, reason] of dangerSignals) { if (normalDescription.includes(keyword)) { score += adjustment; reasons.push(reason); signals += 1 } } for (const [keyword, adjustment, reason] of catastrophicSignals) { if (normalDescription.includes(keyword)) { score += adjustment; reasons.push(reason); signals += 1; catastrophicCount += 1 } } for (const [keyword, adjustment, reason] of mitigatingSignals) { if (normalDescription.includes(keyword)) { score += adjustment; reasons.push(reason); signals += 1 } } const hardCritical = peopleAffected >= 100 || (peopleAffected >= 50 && catastrophicCount > 0) || catastrophicCount >= 2; if (hardCritical) { score = Math.max(score, 90); reasons.push(peopleAffected >= 100 ? 'Mass-casualty escalation: 100 or more people affected' : 'Catastrophic escalation rule applied') } score = Math.max(0, Math.min(100, score)); return { severity: hardCritical ? 'critical' : severityFor(score), score, confidence: hardCritical ? Math.max(94, Math.min(98, 86 + signals * 3)) : Math.min(96, Math.max(78, 78 + signals * 3 + (peopleAffected >= 6 ? 4 : 0))), reasons } }
