import { create } from 'zustand'
import { alerts } from '../data/mock/alerts.mock'
import { hospitals } from '../data/mock/hospitals.mock'
import { incidents } from '../data/mock/incidents.mock'
import { recommendations } from '../data/mock/aiRecommendations.mock'
import { resources } from '../data/mock/resources.mock'
import { riskZones } from '../data/mock/riskZones.mock'
import { validateDispatch } from '../services/dispatchService'
import { isHospitalDestinationEligible, rankHospitalsForIncident } from '../services/hospitalRoutingService'
import { acknowledgeOfflineAction, clearOfflineActions, enqueueOfflineAction, pendingOfflineActionCount } from '../services/offlineQueueService'
import { rankResourcesForIncident } from '../services/resourceAllocationService'
import { createPendingRoute, createPlannedRoute, fetchEmergencyRoute } from '../services/routeService'
import { majorFloodScenario, pauseSimulationTimer, startSimulationTimer } from '../services/simulationEngine'
import { synchronizeLocalActions } from '../services/syncService'
import type { AIRecommendation } from '../types/ai.types'
import type { SystemAlert } from '../types/alert.types'
import type { Hospital } from '../types/hospital.types'
import type { Incident } from '../types/incident.types'
import type { HospitalRecommendation, MedicalDestination } from '../types/hospitalRouting.types'
import type { OfflineAction } from '../types/offline.types'
import type { Resource } from '../types/resource.types'
import type { EmergencyRoute } from '../types/route.types'
import type { RiskZone } from '../types/riskZone.types'
import type { Connectivity, SystemStatus } from '../types/system.types'
import type { DispatchResult } from '../services/dispatchService'
import type { ResourceAllocationRecommendation } from '../services/resourceAllocationService'
import type { SimulationStatus } from '../services/simulationEngine'

interface CrisisState {
  incidents: Incident[]; resources: Resource[]; riskZones: RiskZone[]; hospitals: Hospital[]; alerts: SystemAlert[]; recommendations: AIRecommendation[]; allocationRecommendations: ResourceAllocationRecommendation[]; allocationIncidentId: string | null; hospitalRecommendations: HospitalRecommendation[]; hospitalIncidentId: string | null; selectedHospitalId: string | null; medicalDestinations: MedicalDestination[]; routes: EmergencyRoute[]; system: SystemStatus; selectedIncidentId: string | null; offlineActions: OfflineAction[]; simulationStatus: SimulationStatus; simulationStep: number; simulationEvent: string | null
  setIncidents: (items: Incident[]) => void; upsertIncident: (item: Incident) => void; recordCitizenSos: (item: Incident) => void; removeIncident: (id: string) => void; setResources: (items: Resource[]) => void; upsertResource: (item: Resource) => void; setRiskZones: (items: RiskZone[]) => void; addAlert: (item: SystemAlert) => void; acknowledgeAlert: (id: string) => void; setSystemStatus: (item: SystemStatus) => void; selectIncident: (id: string | null) => void
  setConnectivityStatus: (status: Connectivity) => void; simulateOffline: () => void; simulateDegraded: () => void; simulateOnline: () => void; synchronizePendingActions: () => Promise<void>
  calculateAllocationForSelectedIncident: () => void; calculateHospitalRecommendationsForSelectedIncident: () => void; selectHospitalDestination: (hospitalId: string | null) => void; confirmHospitalDestination: (hospitalId: string, resourceId: string) => boolean; dispatchResource: (resourceId: string, incidentId: string) => DispatchResult; fetchRouteForDispatch: (resourceId: string, incidentId: string) => Promise<void>; fetchRouteToHospital: (resourceId: string, incidentId: string, hospitalId: string) => Promise<void>; retryPendingRoutes: () => void; upsertRoute: (route: EmergencyRoute) => void; removeRoute: (id: string) => void; startSimulation: () => void; pauseSimulation: () => void; resetSimulation: () => void; advanceSimulation: () => void
}
const upsert = <T extends { id: string }>(items: T[], item: T) => items.some(({ id }) => id === item.id) ? items.map((entry) => entry.id === item.id ? item : entry) : [item, ...items]
const cloneInitial = <T,>(value: T): T => structuredClone(value)
const initialSelectedIncidentId = 'inc-001'
let synchronizationInProgress: Promise<void> | null = null
const withPendingCount = (system: SystemStatus, offlineActions: OfflineAction[]): SystemStatus => ({ ...system, pendingSyncActions: pendingOfflineActionCount(offlineActions) })

export const useCrisisStore = create<CrisisState>((set, get) => ({
  incidents, resources, riskZones, hospitals, alerts, recommendations, allocationRecommendations: [], allocationIncidentId: null, hospitalRecommendations: [], hospitalIncidentId: null, selectedHospitalId: null, medicalDestinations: [], routes: [], selectedIncidentId: 'inc-001', offlineActions: [], simulationStatus: 'idle', simulationStep: 0, simulationEvent: null,
  system: { connectivity: 'online', syncStatus: 'idle', lastSyncedAt: '2026-08-14T09:08:00+05:30', activeIncidentCount: 4, activeResourceCount: 5, pendingSyncActions: 0 },
  setIncidents: (incidents) => set({ incidents }), upsertIncident: (item) => set((state) => ({ incidents: upsert(state.incidents, item) })),
  recordCitizenSos: (item) => set((state) => { const offlineActions = state.system.connectivity === 'online' ? state.offlineActions : enqueueOfflineAction(state.offlineActions, { type: 'incident_created', payload: { incidentId: item.id } }); return { incidents: upsert(state.incidents, item), alerts: [{ id: `alert-${item.id}`, severity: item.severity, message: `New citizen SOS received: ${item.title}`, source: 'Citizen SOS', createdAt: item.reportedAt, acknowledged: false, relatedIncidentId: item.id }, ...state.alerts], selectedIncidentId: item.id, offlineActions, system: withPendingCount(state.system, offlineActions) } }),
  removeIncident: (id) => set((state) => ({ incidents: state.incidents.filter((item) => item.id !== id) })), setResources: (resources) => set({ resources }), upsertResource: (item) => set((state) => ({ resources: upsert(state.resources, item) })), setRiskZones: (riskZones) => set({ riskZones }), addAlert: (item) => set((state) => ({ alerts: [item, ...state.alerts] })), acknowledgeAlert: (id) => set((state) => ({ alerts: state.alerts.map((alert) => alert.id === id ? { ...alert, acknowledged: true } : alert) })), setSystemStatus: (system) => set({ system }), selectIncident: (selectedIncidentId) => { set({ selectedIncidentId, selectedHospitalId: null }); get().calculateAllocationForSelectedIncident(); get().calculateHospitalRecommendationsForSelectedIncident() },
  setConnectivityStatus: (connectivity) => { set((state) => ({ system: { ...state.system, connectivity, syncStatus: 'idle' } })); if (connectivity === 'online') void get().synchronizePendingActions() }, simulateOffline: () => get().setConnectivityStatus('offline'), simulateDegraded: () => get().setConnectivityStatus('degraded'), simulateOnline: () => get().setConnectivityStatus('online'),
  synchronizePendingActions: async () => { if (synchronizationInProgress) return synchronizationInProgress; const queuedActions = get().offlineActions; if (!queuedActions.length) { get().retryPendingRoutes(); return } set((state) => ({ system: { ...state.system, connectivity: 'online', syncStatus: 'syncing' } })); synchronizationInProgress = synchronizeLocalActions(queuedActions, (action) => set((state) => { const offlineActions = acknowledgeOfflineAction(state.offlineActions, action.id); return { offlineActions, system: withPendingCount(state.system, offlineActions) } })).then(() => { set((state) => ({ system: { ...state.system, connectivity: 'online', syncStatus: 'idle', lastSyncedAt: new Date().toISOString() } })); get().retryPendingRoutes() }).finally(() => { synchronizationInProgress = null }); return synchronizationInProgress },
  calculateAllocationForSelectedIncident: () => { const state = get(); const incident = state.incidents.find((item) => item.id === state.selectedIncidentId); set({ allocationIncidentId: incident?.id ?? null, allocationRecommendations: incident ? rankResourcesForIncident(incident, state.resources) : [] }) }, calculateHospitalRecommendationsForSelectedIncident: () => { const state = get(); const incident = state.incidents.find((item) => item.id === state.selectedIncidentId); const resource = incident ? state.resources.find((item) => item.assignedIncidentId === incident.id && (item.type === 'ambulance' || item.type === 'medical_team')) : undefined; set({ hospitalIncidentId: incident?.id ?? null, hospitalRecommendations: incident?.type === 'medical' ? rankHospitalsForIncident(incident, state.hospitals, resource) : [] }) }, selectHospitalDestination: (selectedHospitalId) => set({ selectedHospitalId }), upsertRoute: (route) => set((state) => ({ routes: upsert(state.routes, route) })), removeRoute: (id) => set((state) => ({ routes: state.routes.filter((route) => route.id !== id) })),
  dispatchResource: (resourceId, incidentId) => { const state = get(); const resource = state.resources.find((item) => item.id === resourceId); const incident = state.incidents.find((item) => item.id === incidentId); const distanceKm = state.allocationIncidentId === incidentId ? state.allocationRecommendations.find((item) => item.resource.id === resourceId)?.distanceKm : undefined; const result = validateDispatch(resource, incident, distanceKm); if (!result.success || !resource || !incident) return result; const now = new Date().toISOString(); const offlineActions = state.system.connectivity === 'online' ? state.offlineActions : enqueueOfflineAction(state.offlineActions, { type: 'resource_dispatched', payload: { incidentId, resourceId } }); set({ resources: state.resources.map((item) => item.id === resourceId ? { ...item, status: 'dispatched', assignedIncidentId: incidentId, etaMinutes: result.etaMinutes, lastUpdated: now } : item), incidents: state.incidents.map((item) => item.id === incidentId ? { ...item, assignedResourceIds: item.assignedResourceIds.includes(resourceId) ? item.assignedResourceIds : [...item.assignedResourceIds, resourceId], updatedAt: now } : item), offlineActions, system: withPendingCount(state.system, offlineActions) }); get().calculateAllocationForSelectedIncident(); void get().fetchRouteForDispatch(resource.id, incident.id); return result },
  confirmHospitalDestination: (hospitalId, resourceId) => { const state = get(); const incident = state.incidents.find((item) => item.id === state.selectedIncidentId); const hospital = state.hospitals.find((item) => item.id === hospitalId); const resource = state.resources.find((item) => item.id === resourceId); const eligibleHospital = hospital ? isHospitalDestinationEligible(hospital) : false; if (!incident || incident.type !== 'medical' || !hospital || !resource || resource.assignedIncidentId !== incident.id || resource.status !== 'dispatched' || (resource.type !== 'ambulance' && resource.type !== 'medical_team') || !eligibleHospital) return false; const destination = { id: `destination-${incident.id}-${resourceId}`, incidentId: incident.id, resourceId, hospitalId, status: 'en_route' as const, confirmedAt: new Date().toISOString() }; const offlineActions = state.system.connectivity === 'online' ? state.offlineActions : enqueueOfflineAction(state.offlineActions, { type: 'hospital_destination_confirmed', payload: { incidentId: incident.id, hospitalId, resourceId } }); set({ selectedHospitalId: hospitalId, medicalDestinations: upsert(state.medicalDestinations, destination), offlineActions, system: withPendingCount(state.system, offlineActions) }); void get().fetchRouteToHospital(resourceId, incident.id, hospitalId); return true },
  fetchRouteForDispatch: async (resourceId, incidentId) => { const state = get(); const routeId = `route-${resourceId}-${incidentId}`; const existingRoute = state.routes.find((route) => route.id === routeId); if (existingRoute?.status === 'active' || existingRoute?.status === 'planned') return; const resource = state.resources.find((item) => item.id === resourceId); const incident = state.incidents.find((item) => item.id === incidentId); if (!resource || !incident || resource.status !== 'dispatched' || resource.assignedIncidentId !== incident.id) return; if (state.system.connectivity === 'offline') { set((current) => ({ routes: upsert(current.routes, { ...createPendingRoute(resource.id, incident.id, 'Road routing is pending until connectivity returns.'), incidentId, stage: 'incident' }) })); return } set((current) => ({ routes: upsert(current.routes, { ...createPlannedRoute(resource.id, incident.id), incidentId, stage: 'incident' }) })); try { const route = await fetchEmergencyRoute(resource.id, resource.location, incident.id, incident.location); set((current) => ({ routes: upsert(current.routes, { ...route, incidentId, stage: 'incident' }), resources: current.resources.map((item) => item.id === resource.id ? { ...item, etaMinutes: Math.max(1, Math.ceil(route.durationSeconds! / 60)) } : item) })) } catch (error) { const message = error instanceof Error ? error.message : 'Unable to calculate route.'; set((current) => ({ routes: upsert(current.routes, { ...createPendingRoute(resource.id, incident.id, message), incidentId, stage: 'incident', status: current.system.connectivity === 'degraded' ? 'pending' : 'blocked' }) })) } },
  fetchRouteToHospital: async (resourceId, incidentId, hospitalId) => { const state = get(); const resource = state.resources.find((item) => item.id === resourceId); const hospital = state.hospitals.find((item) => item.id === hospitalId); if (!resource || !hospital) return; const pending = (message: string) => set((current) => ({ routes: upsert(current.routes, { ...createPendingRoute(resourceId, hospitalId, message), incidentId, stage: 'hospital' }) })); if (state.system.connectivity === 'offline') { pending('Hospital route is pending until connectivity returns.'); return } set((current) => ({ routes: upsert(current.routes, { ...createPlannedRoute(resourceId, hospitalId), incidentId, stage: 'hospital' }) })); try { const route = await fetchEmergencyRoute(resourceId, resource.location, hospitalId, hospital.location); set((current) => ({ routes: upsert(current.routes, { ...route, incidentId, stage: 'hospital' }) })) } catch (error) { const message = error instanceof Error ? error.message : 'Unable to calculate hospital route.'; set((current) => ({ routes: upsert(current.routes, { ...createPendingRoute(resourceId, hospitalId, message), incidentId, stage: 'hospital', status: current.system.connectivity === 'degraded' ? 'pending' : 'blocked' }) })) } },
  retryPendingRoutes: () => { if (get().system.connectivity !== 'online') return; get().routes.filter((route) => (route.status === 'pending' || route.status === 'blocked') && route.stage !== undefined).forEach((route) => { if (route.stage === 'hospital' && route.incidentId) void get().fetchRouteToHospital(route.resourceId, route.incidentId, route.destinationId); else if (route.incidentId) void get().fetchRouteForDispatch(route.resourceId, route.incidentId); }) },
  startSimulation: () => { const state = get(); if (state.simulationStatus === 'completed') get().resetSimulation(); set({ simulationStatus: 'running', simulationEvent: state.simulationStep ? state.simulationEvent : majorFloodScenario[0].message, selectedIncidentId: 'inc-001' }); get().calculateAllocationForSelectedIncident(); startSimulationTimer(get().advanceSimulation) }, pauseSimulation: () => { pauseSimulationTimer(); set({ simulationStatus: 'paused' }) },
  resetSimulation: () => { pauseSimulationTimer(); const restoredIncidents = cloneInitial(incidents); const restoredResources = cloneInitial(resources); set((state) => ({ incidents: restoredIncidents, resources: restoredResources, riskZones: cloneInitial(riskZones), hospitals: cloneInitial(hospitals), alerts: cloneInitial(alerts), recommendations: cloneInitial(recommendations), routes: [], selectedIncidentId: initialSelectedIncidentId, allocationIncidentId: initialSelectedIncidentId, allocationRecommendations: rankResourcesForIncident(restoredIncidents.find((item) => item.id === initialSelectedIncidentId)!, restoredResources), hospitalRecommendations: [], hospitalIncidentId: null, selectedHospitalId: null, medicalDestinations: [], offlineActions: clearOfflineActions(), system: { ...state.system, pendingSyncActions: 0, syncStatus: 'idle' }, simulationStatus: 'idle', simulationStep: 0, simulationEvent: null })) },
  advanceSimulation: () => { const state = get(); if (state.simulationStatus !== 'running') return; const event = majorFloodScenario[state.simulationStep]; const flood = state.incidents.find((item) => item.id === 'inc-001'); if (!event || !flood) return; if (event.requiresOperator && !flood.assignedResourceIds.some((id) => state.resources.find((resource) => resource.id === id)?.status === 'dispatched')) { pauseSimulationTimer(); set({ simulationStatus: 'paused', simulationEvent: event.message }); return } const nextStep = state.simulationStep + 1; const route = state.routes.find((item) => item.destinationId === flood.id && item.status === 'active'); if (event.step === 3 && route?.path.length) set({ resources: state.resources.map((resource) => resource.id === route.resourceId ? { ...resource, location: route.path[Math.min(route.path.length - 1, Math.ceil(route.path.length * .6))], etaMinutes: Math.max(1, Math.ceil((route.durationSeconds ?? 60) / 120)) } : resource) }); if (event.step === 4) set({ riskZones: state.riskZones.map((zone) => zone.id === 'zone-1' ? { ...zone, confidence: 96, reason: 'Floodwater expansion detected during live simulation.' } : zone), alerts: [{ id: 'sim-flood-risk', severity: 'high', message: event.message, source: 'Live crisis simulation', createdAt: new Date().toISOString(), acknowledged: false, relatedIncidentId: flood.id }, ...state.alerts] }); if (event.step === 5) { pauseSimulationTimer(); set({ simulationStatus: 'completed', simulationStep: nextStep, simulationEvent: event.message, incidents: state.incidents.map((item) => item.id === flood.id ? { ...item, status: 'contained' } : item), resources: state.resources.map((resource) => resource.assignedIncidentId === flood.id ? { ...resource, status: 'available', assignedIncidentId: null, etaMinutes: null } : resource) }); return } set({ simulationStep: nextStep, simulationEvent: event.message }) },
}))
